if not REWINDER then REWINDER = {} end

local M = {
   SAVE_ENTRY_W = 8.9,
   KEY_SAVE_COLOR = {0.2, 0.7, 0.7, 1},
   FILTER_BUTTON_W = 3.6,
   ICON_BUTTON_SIDE = 0.90,
   ICON_BUTTON_ICON_SIZE = 0.60,
   ICON_BUTTON_PADDING = 0.08,
   ICON_BUTTON_RADIUS = 0.1,
   ICON_BUTTON_BORDER = 0.04,
}

M.MODE_ROW_HALF_W = M.SAVE_ENTRY_W * 0.5

REWINDER.KEY_SAVE_COLOR = M.KEY_SAVE_COLOR

return M
